monitor.alsa.rules = [
	{matches = [{
        node.name = "alsa_output.pci-0000_01_00.1.hdmi-stereo"
	}]
    actions = { update-props = {
		node.disabled = true
	}}},

	{matches = [{
        node.name = "alsa_output.usb-BurrBrown_from_Texas_Instruments_USB_AUDIO_CODEC-00.analog-stereo"
	}]
    actions = { update-props = {
		node.disabled = true
	}}},

	{matches = [{
        node.name = "alsa_input.pci-0000_00_1f.3.analog-stereo"
	}]
    actions = { update-props = {
		node.disabled = true
	}}},
]
